"""Preview-track ID lookup table.

The catalogue lives in ``assets/previews.json`` (regenerated by
``tools/fetch_previews.py``). At import time we build a flat dict
mapping ``(song, performer)`` to a Deezer track ID; the runtime calls
:func:`track_id_for` to decide whether to render a Play button.

Why we don't store the URL: Deezer signs preview URLs with a short-
lived expiry token, so the URL has to be fetched at click-time. The
track ID is stable forever.
"""

from __future__ import annotations

import json
import os
from typing import Dict, Optional, Tuple


HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
JSON_PATH = os.path.join(ROOT, "assets", "previews.json")


_table: Dict[Tuple[str, str], int] = {}


def _load() -> None:
    if not os.path.isfile(JSON_PATH):
        return
    try:
        with open(JSON_PATH, "r", encoding="utf-8") as f:
            raw = json.load(f)
    except (OSError, json.JSONDecodeError):
        return
    for key, entry in raw.items():
        if "::" not in key:
            continue
        song, performer = key.split("::", 1)
        tid = entry.get("deezer_track_id")
        if isinstance(tid, int):
            _table[(song, performer)] = tid


_load()


def track_id_for(song: str, performer: str) -> Optional[int]:
    return _table.get((song, performer))


def has_preview(song: str, performer: str) -> bool:
    return (song, performer) in _table
